name: nn_env
channels:
    - defaults
    - pytorch-nightly
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - gensim
    - h5py
    - torch
    - torchinfo
    - tqdm
    - numpy
    - pandas
    - scikit-learn
    - seaborn
    - matplotlib
    - jupyterlab
    - mlflow
